[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "http://172.16.105.12:5000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://172.16.105.12:5000/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"} 