services:
  # Frontend
  - type: web
    name: app-monitor-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: app-monitor-backend
          property: host
      - key: REACT_APP_WS_URL
        fromService:
          type: web
          name: app-monitor-backend
          property: host
          replacer:
            from: https
            to: wss

  # Backend
  - type: web
    name: app-monitor-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: app-monitor-db
          property: connectionString

databases:
  - name: app-monitor-db
    databaseName: appmonitor
    plan: free 